### ISSUE TITLE
Font data license.

### ISSUE THREAD

**Issue by 610t** [linclip/M5AtomMatrix_DispChar#1]
I want to use this font data for other project.
What is the license for this font data?

**Comment by linclip** [comment]
The ASCII fonts in this library are based on the following libraries
https://github.com/microsoft/pxt-microbit
Therefore, it is MIT licensed.

返信が遅れてすみません。
このライブラリのASCIIフォントは以下のライブラリをベースにしています。
https://github.com/microsoft/pxt-microbit
よって、MITライセンスとなります。

**Comment by 610t** [comment]
Thank you very much.
Now I know it is available for my project.

ありがとうございました。
これで、私のプロジェクトで利用できることがわかりました。
